### Unit 2.1.1 NumPy

In [8]:
import numpy as np

In [7]:
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [4]:
#Adding dimensions to array manually
w = np.array([[0,1,2,3],[4,5,6,7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
#Adding dimensions to array with np.arange() and np.reshape().
##For array range (arange) starting from 0 to 8, not including 8, create two four-item arrays.
y = np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
#Element-wise functions processes array elements one at a tie and then returns a new array.  
#Use element-wise functions when you want to transform each individual element in an array 
#   and get back a collection of all results

x = np.array([0,1,2,3])

#Square each value
print(np.square(x))

#Square root each value
print(np.sqrt(x))

#Cosine of each value
print(np.cos(x))

#These methods return arrays the same length as the input array.  

[0 1 4 9]
[ 0.          1.          1.41421356  1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [12]:
#Aggregator functions aggregate elements of an array to return a single value
x = np.array([0,1,2,3])

#Find the max value
print(np.max(x))

#Find min value
print(np.min(x))

#Find mean of input array
print(np.mean(x))

#Find standard deviation of input array
print(np.std(x))

3
0
1.5
1.11803398875
